### ISSUE TITLE
Resister network 1

### ISSUE THREAD

**Issue by ghhann** [mahjongg2/ZX81plus38#12]
Wanted to double check that r1 should be 10k as the farnell part number is for a 4.7k

Best

**Comment by mahjongg2** [comment]
both 4K7 and 10K will work, I will correct the BOM so that RP1 will be 10K.

**Comment by ghhann** [comment]
Thanks!!

**Comment by mahjongg2** [comment]
Uploaded a new (revision 1.10) BOM, with the correct order code for RP1

**Comment by mahjongg2** [comment]
uploaded revision 1.10 of the bom with a corrected order code for RP1 from farnell, now 10K x 6
